### PR TITLE
Mathematica Wrapper Units Patch for Mathematica 13.2

### LINKED ISSUE #495: Mathematica 13.2 Breaks Unit Handling in Mathematica Wrapper
### Description

Mathematica 13.2 breaks some unit handling employed in the RefpropLink paclet; Specifically the definition of Newton (N) and Ferenheit (°F) in the underlying RefpropUnits code.

### Steps to Reproduce

1. Just load the RefpropLink wrapper per usual with 
```WL
Needs["RefpropLink`"]
```

**Expected behavior:** No errors on load and accurate behavior of pre-defined units.

**Actual behavior:** 
1. Loading RefpropLink throws an error, at which point there is confusion between N, Newton, and Newtons.
```WL
Quantity: Unable to interpret unit specification 1. N .
```

2. Applying pre-defined unit, °F, results in non-sensical unit conversion
```WL
In[1] T = 72 °F
Out[1] 18426.8 K
```

These are the only issues discovered so far.  Basic REFPROP wrapper functionality is still working.

### Versions

**REFPROP Version:** REFPROP 10  
**Operating System and Version:** Windows 10 
**Access Method:** Mathematica Wrapper (Mathematica 13.2 - Recent Update)

### Additional Information

Working on fixing this.  
**_Suggest not upgrading to 13.2 just yet until a patch is created._**

Suspect some duplicate symbol definitions are now bleeding over to create conflicts with unit symbols initialized when RefpropLink is loaded.
* The symbol "N" has always been a built-in numeric evaluation function, but now seems to be causing a conflict with definition of "Newton".  This wasn't a problem before, but there's a simple fix for this.
* This one may be more problematic as the application of the affine unit, °F, seems to have changed in 13.2.  May need another way to represent this unit easily or limit users to native `Quantity` definitions for "DegreesFerenheit" or absolute units.  Additionally, `K` is now a pre-defined symbol in 13.2 (it wasn't before), which may be causing a conflict.
* Further investigation shows that this second issue may be a bug in Mathematica 13.2.  As of version 13.2, Temperature units now come in two types, `Absolute` and `Difference`.  For example, Rankine units are represented as "DegreesRankine" (Absolute) and "DegreesRankineDifference" (difference unit).  However, some straight-forward unit conversions (without RepropLink loaded) show that when converting to/from affine temperature units of °F and °C,  "DegreesRankine" is being treated as a **_difference_** unit and not an absolute units.  This may be creating all kinds of repercussions.  Currently investigating this issue with Wolfram.

### PR DESCRIPTION
**Pull request by henningjp**
### Description of the Change

Mathematica 13.2 introduced some changes in unit handling that created errors in the Mathematica Wrapper.  These have been patched including:
- On loading of RefpropLink, an error occurs on the definition of the mN unit.
- Mathematica bug treats Rankine (R) unit as a temperature change unit instead of an absolute unit.  Wolfram will provide a patch release, but provided an interim work around that is applied when RefpropLink loads, but only if $VersionNumber = 13.2
- There is a fundamental change in how Mathematica handles multiplication of affine temperature units (°F and °C).  The change is warranted, but RefpropLink took advantage of the previously inconsistent treatment to create temperature unit variables °F and °C for simply temperature input notation.  These unit variables have been removed for all versions > 13.2.

### Benefits

Eliminates error message when loading the RefpropLink wrapper paclet, and when converting between Rankine and other temperature units.  Also deprecates the affine temperature scaling variable definitions for °F and °C.

### Possible Drawbacks

Temperatures with affine units must now be entered using Mathematica's `Quantity[ ]` function.

```WL
    T = Quantity[72.0, "DegreesFahrenheit"]
    T2 = Quantity[22.0, "DegreesCelsius"]
```

Also, extensive documentation still uses the provided °F and °C unit variables.  However, an upcoming PR to address #502 will correct this misuse of °F and °C in the overhauled documentation  files.

### Verification Process

Changes were rather simple and can be viewed in the file changes.  However, documentation examples were re-run and did not show any errors.

### Applicable Issues

Closes #495

### CODE REVIEW

File: wrappers/Mathematica/RefpropLink/RefpropLink.m [hunk 1]
```diff
@@ -306,20 +312,39 @@
...
+If[ $VersionNumber == 13.2,                     (* ONLY if Mathematica version 12.2     *)
+    QuantityUnits`Private`hasNonZeroTempUnitQ["DegreesRankine"]=True;  (*  Workaround  *)
+];                                              (* Set R as absolute quantity          *)
+
+
 (***************************************************************************************)
 (*                            Package initialization Complete                          *)
 (***************************************************************************************)
 
+
```
Comment (ianhbell) [inline wrappers/Mathematica/RefpropLink/RefpropLink.m:332]: Can you please remove all the added whitespace in this file?

Comment (henningjp) [reply wrappers/Mathematica/RefpropLink/RefpropLink.m]: Done.  Whitespace removed using VS Code.

Since the plan is to only edit in Mathematica after this as the IDE with error checking, syntax highlighting, etc., these blank lines will eventually need be added back in, but we can do that with a separate, stand-alone PR where we're not trying to identify changes to the files.

Re-ran basic tests and all is functioning correctly with no errors.

**Comment by ianhbell** [comment]
This one is good too, right>
